// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace apitest.Migrations
{
    [DbContext(typeof(GenerateurSecuriteOTPDbContext))]
    partial class GenerateurSecuriteOTPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenSecurOTP.Models.CodeOTP", b =>
                {
                    b.Property<int>("IDOTP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDOTP"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateExp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateGen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDOTP");

                    b.HasIndex("Username");

                    b.ToTable("CodesOtp");
                });

            modelBuilder.Entity("GenSecurOTP.Models.CodeSecurite", b =>
                {
                    b.Property<int>("IDCS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCS"));

                    b.Property<string>("CodeSec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateGen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDCS");

                    b.HasIndex("Username");

                    b.ToTable("CodesSecurite");
                });

            modelBuilder.Entity("GenSecurOTP.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GSM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GenSecurOTP.Models.CodeOTP", b =>
                {
                    b.HasOne("GenSecurOTP.Models.User", "User")
                        .WithMany("CodesOtp")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenSecurOTP.Models.CodeSecurite", b =>
                {
                    b.HasOne("GenSecurOTP.Models.User", "User")
                        .WithMany("CodesSecurite")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenSecurOTP.Models.User", b =>
                {
                    b.Navigation("CodesOtp");

                    b.Navigation("CodesSecurite");
                });
#pragma warning restore 612, 618
        }
    }
}
